### ISSUE TITLE
Tags are not imported from NETSCAPE-Bookmark-file

### ISSUE THREAD

**Issue by generall** [RadhiFadlillah/shiori#34] opened 2018-03-02 22:33 UTC
I have NETSCAPE-Bookmark-file exported from Firefox. It contains `TAGS` parameter with tags for each bookmark. It would be nice if shiori could import this tags.

**Comment by skx** [comment] 2018-03-03 06:09
This issue is a duplicate of #28.

**Closed** 2018-03-03 10:00 UTC
