### ISSUE TITLE
Panic while adding a tag to an existing bookmark

### ISSUE THREAD

**Issue by Hunter-Github** [RadhiFadlillah/shiori#78] opened 2018-03-13 02:54 UTC
Version: 6bab302785263e942ee50421fda500316fa253b0
OS: Linux (Debian 9)
Browser: Chromium 67.0.3369.0
Problem: shiori serve doesn't handle progress bar panics gracefully (?)
Actions: import bookmarks, then import bookmarks again (with some additions), then edit tags for 1 card (success, checked via the next run of shiori), then edit tags for another bookmark card (failure, panic, server down)
Reproducibility: same stuff on the 2nd try (the first bookmark edit succeeds, the second one fails)

```
Fetching new bookmarks data
   0s [====================================================================] 100%

Saving new data
   0s [====================================================================] 100%
  --- [--------------------------------------------------------------------]   0%
panic: close of closed channel

goroutine 2955 [running]:
github.com/gosuri/uiprogress.(*Progress).Listen(0xc42007a180)
        /home/xxx/gofiles/src/github.com/gosuri/uiprogress/progress.go:117 +0x160
created by github.com/gosuri/uiprogress.(*Progress).Start
        /home/xxx/gofiles/src/github.com/gosuri/uiprogress/progress.go:134 +0x3f
```

**Comment by gissehel** [comment] 2018-04-09 21:59
I've got the same issue. It always works for the first tag change, and always fails for the second one.

Here is the exact exhaustive easy steps to reproduce:

docker image used: latest available (8fe4587a0f6a)

Steps to reproduce
============

Requierements
----------------

* Docker
* sudo access & root access to /tmp (not mandatory, both can be changed by tweeking the command lines below)

Steps
------

```
sudo rm -f /tmp/shiori.db
sudo touch /tmp/shiori.db
docker rm -f shiori-test-step1
docker rm -f shiori-test-step2
docker rm -f shiori-test-step3
docker run -ti --volume /tmp/shiori.db:/srv/shiori.db:rw --name shiori-test-step1 radhifadlillah/shiori /usr/local/bin/shiori account add test
```

Here put `testtest` as password

```
docker run -ti --volume /tmp/shiori.db:/srv/shiori.db:rw --name shiori-test-step2 radhifadlillah/shiori /usr/local/bin/shiori add http://www.google.com/
docker run -ti -p 8080:8080 --volume /tmp/shiori.db:/srv/shiori.db:rw --name shiori-test-step3 radhifadlillah/shiori
```

* browse the web site on ip:8080 
* Login with test/testtest
* Edit the tag of the only entry "google"
* Put "#test" as a tag
* Check the test is "test"
* Edit the tag of the only entry "google"
* Put "test2" as a tag

Expected result
-----------------
* The tag is now "#test2"

Actual result
--------------
* Network error (or error 502 while browsing threw nginx reverse proxy) on the web site 
* `panic: close of closed channel` on the server stderr

**Comment by gissehel** [comment] 2018-04-10 20:09
I worked around the problem by commenting the 5 lines referencing uiprogress in cmd/update.go (import, Start, AddBar, bar.Incr and Stop).

No more progress bars, but no more crash

**Comment by gissehel** [comment] 2018-04-29 09:46
The issue doesn't seem to be present anymore after refactoring in commit 2c23f98 as the progress bars only seems to be diplayed in interactive commands and not in serve command anymore.

**Comment by RadhiFadlillah** [comment] 2018-05-26 15:08
Since it seems it's already fixed, I will close this issue for now.

**Closed by RadhiFadlillah** 2018-05-26 15:08 UTC
